version: "3.7"
services:
  zookeeper:
    restart: always
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-volume:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    restart: always
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092" # Kafka port for internal communication
    volumes:
      - "kafka1-volume:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  kafka2:
    restart: always
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9093:9093" # Kafka port for external communication
    volumes:
      - "kafka2-volume:/bitnami"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  kafka3:
    restart: always
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9094:9094" # Kafka port for external communication
    volumes:
      - "kafka3-volume:/bitnami"
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:9094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    restart: always
    environment:
      - KAFKA_BROKERCONNECT=kafka1:9092,kafka2:9093,kafka3:9094
      - KAFKA_ZOOKEEPERCONNECT=zookeeper:2181
    ports:
      - "9000:9000"  # Kafdrop web UI
    depends_on:
      - kafka1
      - kafka2
      - kafka3

volumes:
  kafka1-volume:
  kafka2-volume:
  kafka3-volume:
  zookeeper-volume:
